import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { BrowserRouter as Router, Routes, Route } from "react-router-dom";
import SignIn from "./pages/AuthPages/SignIn";
import SignUp from "./pages/AuthPages/SignUp";
import ForgotPassword from "./pages/AuthPages/ForgotPassword";
import NotFound from "./pages/OtherPage/NotFound";
import Home from "./pages/Dashboard/Home";
import Calendar from "./pages/Calendar";
import Blank from "./pages/Blank";
import FormElements from "./pages/Forms/FormElements";
import BasicTables from "./pages/Tables/BasicTables";
import Alerts from "./pages/UiElements/Alerts";
import Avatars from "./pages/UiElements/Avatars";
import Badges from "./pages/UiElements/Badges";
import Buttons from "./pages/UiElements/Buttons";
import Images from "./pages/UiElements/Images";
import Videos from "./pages/UiElements/Videos";
import LineChart from "./pages/Charts/LineChart";
import BarChart from "./pages/Charts/BarChart";
import AppLayout from "./layout/AppLayout";
import ProtectedRoute from "./components/ProtectedRoute";
import { ScrollToTop } from "./components/common/ScrollToTop";
import PublicRoute from "./components/PublicRoute";
import Company from "./pages/Company/Company";
import AddCompany from "./pages/Company/AddCompany";
import Pegawai from "./pages/Pegawai/Pegawai";
import AddPegawai from "./pages/Pegawai/AddPegawai";
import EditCompany from "./pages/Company/EditCompany";
import Role from "./pages/Role/Role";
import AddRole from "./pages/Role/AddRole";
import Kontrak from "./pages/Kontrak/kontrak";
import DivisiPage from "./pages/Divisi/divisi";
import AddKontrak from "./pages/Kontrak/AddKontrak";
import EditKontrak from "./pages/Kontrak/EditKontrak";
import EditRole from "./pages/Role/EditRole";
import EditPegawai from "./pages/Pegawai/EditPegawai";
import PegawaiForm from "./components/Pegawai/PegawaiForm";
import PegawaiKeluar from "./pages/PegawaiKeluar/PegawaiKeluar";
import AddPegawaiKeluar from "./pages/PegawaiKeluar/AddPegawaiKeluar";
import AddDivisi from "./pages/Divisi/AddDivisi";
import EditDivisi from "./pages/Divisi/EditDivisi";
import Shift from "./pages/Shift/Shift";
import AddShift from "./pages/Shift/AddShift";
import EditShift from "./pages/Shift/EditShift";
import LokasiPage from "./pages/Lokasi/Lokasi";
import AddLokasi from "./pages/Lokasi/AddLokasi";
import EditLokasi from "./pages/Lokasi/EditLokasi";
import "./styles/datepicker.css";
import CutiPage from "./pages/Cuti/Cuti";
import AddCuti from "./pages/Cuti/AddCuti";
import Penugasan from "./pages/Penugasan/Penugasan";
import AddPenugasan from "./pages/Penugasan/AddPenugasan";
import EditPenugasan from "./pages/Penugasan/EditPenugasan";
import Rapat from "./pages/Rapat/Rapat";
import AddRapat from "./pages/Rapat/AddRapat";
import EditRapat from "./pages/Rapat/EditRapat";
import JenisKinerja from "./pages/JenisKinerja/JenisKinerja";
import AddJenisKinerja from "./pages/JenisKinerja/AddJenisKinerja";
import EditJenisKinerja from "./pages/JenisKinerja/EditJenisKinerja";
import InventoryPage from "./pages/Inventory/Inventory";
import LaporanKinerja from "./pages/Laporan Kinerja/LaporanKinerja";
import AddInventory from "./pages/Inventory/AddInventory";
import EditInventory from "./pages/Inventory/EditInventory";
import KinerjaPegawaiPage from "./pages/Kinerja Pegawai/KinerjaPegawai";
import LaporanKerjaPage from "./pages/Laporan Kerja/LaporanKerja";
import DataAbsen from "./pages/Absensi/DataAbsen";
import DataDinasLuar from "./pages/DinasLuar/DataDinasLuar";
import KategoriReimbursement from "./pages/Reimbursement/KategoriReimbursement";
import AddKategoriReimbursement from "./pages/Reimbursement/AddKategoriReimbursement";
import EditKasbon from "./pages/Kasbon/EditKasbon";
import EditKategoriReimbursement from "./pages/Reimbursement/EditKategoriReimbursement";
import BeritaPage from "./pages/Berita dan Informasi/Berita";
import AddBerita from "./pages/Berita dan Informasi/AddBerita";
import EditBerita from "./pages/Berita dan Informasi/EditBerita";
import Reimbursements from "./pages/Reimbursements/Reimbursements";
import AddReimbursement from "./pages/Reimbursements/AddReimbursement";
import AddShiftMapping from "./pages/Mapping Shift dan dinas luar/AddShiftMapping";
import PegawaiShiftPage from "./pages/User Interface/Absen/PegawaiShiftPage";
import JadwalShiftPegawai from "./pages/User Interface/Jadwal Shift/JadwalShiftPegawai";
import PegawaiHome from "./pages/User Interface/Home/PegawaiHome";
import DataLembur from "./pages/Lembur/DataLembur";
import AddReimbursementPegawai from "./pages/User Interface/Reimbursement/AddReimbursementPegawai";
import ReimbursementPegawai from "./pages/User Interface/Reimbursement/ReimbursementPegawai";
import EditReimbursementPegawai from "./pages/User Interface/Reimbursement/EditReimbursementPegawai";
import KasbonPegawai from "./pages/User Interface/Kasbon/KasbonPegawai";
import Kasbon from "./pages/Kasbon/Kasbon";
import AddKasbonPegawai from "./pages/User Interface/Kasbon/AddKasbonPegawai";
import AddKasbon from "./pages/Kasbon/AddKasbon";
import EditKasbonPegawai from "./pages/User Interface/Kasbon/EditKasbonPegawai";
import CutiPegawai from "./pages/User Interface/Cuti/CutiPegawai";
import AddCutiPegawai from "./pages/User Interface/Cuti/AddCutiPegawai";
import EditCutiPegawai from "./pages/User Interface/Cuti/EditCutiPegawai";
import AddDinasLuarMapping from "./pages/Mapping Shift dan dinas luar/AddDinasLuarMapping";
import JadwalDinasLuarMappingPegawai from "./pages/User Interface/Jadwal Dinas Luar Mapping/JadwalDinasLuarMappingPegawai";
import DinasLuarPegawaiPage from "./pages/User Interface/Absen/DinasLuarPegawaiPage";
import LemburPegawaiPage from "./pages/User Interface/Absen/LemburPegawaiPage";
import HistoryAbsenPegawaiPage from "./pages/User Interface/History/HistoryAbsenPegawai";
import HistoryDinasPegawai from "./pages/User Interface/History/HistoryDinasPegawai";
import HistoryLemburPegawai from "./pages/User Interface/History/HistoryLemburPegawai";
import AllMenuPegawai from "./pages/User Interface/Home/AllMenuPegawai";
import Dokumen from "./pages/Dokumen Pegawai/Dokumen";
import AddDokumen from "./pages/Dokumen Pegawai/AddDokumen";
import EditDokumen from "./pages/Dokumen Pegawai/EditDokumen";
import DokumenPegawai from "./pages/User Interface/Dokumen Pegawai/DokumenPegawai";
import AddDokumenPegawai from "./pages/User Interface/Dokumen Pegawai/AddDokumenPegawai";
import EditDokumenPegawai from "./pages/User Interface/Dokumen Pegawai/EditDokumenPegawai";
import BeritaDetail from "./pages/User Interface/Berita dan Informasi/BeritaDetail";
import BeritaList from "./pages/User Interface/Home/BeritaList";
import AddKunjungan from "./pages/Kunjungan/AddKunjungan";
import KunjunganPage from "./pages/Kunjungan/Kunjungan";
import VisitOutKunjungan from "./pages/Kunjungan/VisitOutKunjungan";
import KunjunganPegawai from "./pages/User Interface/Kunjungan/KujunganPegawai";
import AddVisitInPegawai from "./pages/User Interface/Kunjungan/AddVisitInPegawai";
import VisitOutPegawai from "./pages/User Interface/Kunjungan/VisitOutPegawai";
import PenugasanPegawai from "./pages/User Interface/Penugasan/PenugasanPegawai";
import DetailPenugasan from "./pages/User Interface/Penugasan/DetailPenugasan";
import RapatPegawai from "./pages/User Interface/Rapat/RapatPegawai";
import RapatPegawaiDetail from "./pages/User Interface/Rapat/RapatPegawaiDetail";
import InventoryPegawai from "./pages/User Interface/Inventory/InventoryPegawai";
import AddInventoryPegawai from "./pages/User Interface/Inventory/AddInventoryPegawai";
import ChangePasswordPegawai from "./pages/User Interface/ChangePassword/ChangePasswordPegawai";
import MyProfilePegawai from "./pages/User Interface/Profile/MyProfilePegawai";
import RekapData from "./pages/RekapSummary/RekapSummary";
import LaporanKinerjaPegawai from "./pages/User Interface/Laporan Kinerja/LaporanKinerjaPegawai";
import LaporanKerjaPegawai from "./pages/User Interface/Laporan Kerja/LaporanKerjaPegawai";
import AddLaporanKerjaPegawai from "./pages/User Interface/Laporan Kerja/AddLaporanKerjaPegawai";
import LaporanKerjaDetailPegawai from "./pages/User Interface/Laporan Kerja/LaporanKerjaDetailPegawai";
import EditLaporanKerjaPegawai from "./pages/User Interface/Laporan Kerja/EditLaporanKerjaPegawai";
import ShiftRequestApproval from "./pages/Shift/ShiftRequestApproval";
import FaceEnroll from "./pages/User Interface/Face Recognition/FaceEnroll";
import Payroll from "./pages/Payroll/Payroll";
import HitungGajiPegawai from "./pages/RekapSummary/HitungGajiPegawai";
import EditPayrollPegawai from "./pages/Payroll/EditPayrollPegawai";
import KontrakPegawai from "./pages/Kontrak/KontrakPegawai";
import PenggajianPegawai from "./pages/User Interface/Payroll/PenggajianPegawai";
import Notification from "./pages/Notification/Notification";
import NotificationPegawai from "./pages/User Interface/Notifications/NotificationPegawai";
import FaceRecognition from "./pages/Absensi/FaceRecognition";
import FaceRecognitionRegisterPegawai from "./pages/User Interface/Face Recognition/FaceRecognitionRegisterPegawai";
import ProfilePage from "./pages/ProfilePage";
import ResetPassword from "./pages/AuthPages/ResetPassword";
import EditAbsen from "./pages/Absensi/EditAbsen";
export default function App() {
    return (_jsxs(Router, { children: [_jsx(ScrollToTop, {}), _jsxs(Routes, { children: [_jsx(Route, { path: "/", element: _jsxs(PublicRoute, { children: [_jsx(SignIn, {}), " "] }) }), _jsx(Route, { path: "/signup", element: _jsx(PublicRoute, { children: _jsx(SignUp, {}) }) }), _jsx(Route, { path: "/forgot-password", element: _jsx(PublicRoute, { children: _jsx(ForgotPassword, {}) }) }), _jsx(Route, { path: "/reset-password", element: _jsx(PublicRoute, { children: _jsx(ResetPassword, {}) }) }), _jsx(Route, { path: "/home-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(PegawaiHome, {}) }) }), _jsx(Route, { path: "/shift-mapping/self/:pegawai_id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(JadwalShiftPegawai, {}) }) }), _jsx(Route, { path: "/add-kunjungan-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(AddVisitInPegawai, {}) }) }), _jsx(Route, { path: "/notification", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(NotificationPegawai, {}) }) }), _jsx(Route, { path: "/kunjungan-pegawai/visit-out/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(VisitOutPegawai, {}) }) }), _jsx(Route, { path: "/penugasan/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(DetailPenugasan, {}) }) }), _jsx(Route, { path: "/penugasan-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(PenugasanPegawai, {}) }) }), _jsx(Route, { path: "/dinas-luar/self/:pegawai_id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(JadwalDinasLuarMappingPegawai, {}) }) }), _jsx(Route, { path: "/change-password-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(ChangePasswordPegawai, {}) }) }), _jsx(Route, { path: "/my-profile-pegawai/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(MyProfilePegawai, {}) }) }), _jsx(Route, { path: "/face-recog-regis/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(FaceRecognitionRegisterPegawai, {}) }) }), _jsx(Route, { path: "/absensi/pegawai/:pegawai_id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(PegawaiShiftPage, {}) }) }), _jsx(Route, { path: "/absensi-lembur/pegawai/:pegawai_id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(LemburPegawaiPage, {}) }) }), _jsx(Route, { path: "/absensi-dinas-luar/pegawai/:pegawai_id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(DinasLuarPegawaiPage, {}) }) }), _jsx(Route, { path: "/dokumen/:pegawai_id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(DokumenPegawai, {}) }) }), _jsx(Route, { path: "/reimbursement-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(ReimbursementPegawai, {}) }) }), _jsx(Route, { path: "/payroll-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(PenggajianPegawai, {}) }) }), _jsx(Route, { path: "/add-reimbursement-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(AddReimbursementPegawai, {}) }) }), _jsx(Route, { path: "/edit-reimbursement-pegawai/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(EditReimbursementPegawai, {}) }) }), _jsx(Route, { path: "/edit-dokumen-pegawai/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(EditDokumenPegawai, {}) }) }), _jsx(Route, { path: "/berita/pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(BeritaList, {}) }) }), _jsx(Route, { path: "/berita/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(BeritaDetail, {}) }) }), _jsx(Route, { path: "/kasbon-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(KasbonPegawai, {}) }) }), _jsx(Route, { path: "/laporan-kinerja-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(LaporanKinerjaPegawai, {}) }) }), _jsx(Route, { path: "/laporan-kerja-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(LaporanKerjaPegawai, {}) }) }), _jsx(Route, { path: "/add-laporan-kerja-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(AddLaporanKerjaPegawai, {}) }) }), _jsx(Route, { path: "/laporan-kerja/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(LaporanKerjaDetailPegawai, {}) }) }), _jsx(Route, { path: "/edit-laporan-kerja/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(EditLaporanKerjaPegawai, {}) }) }), _jsx(Route, { path: "/add-kasbon-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(AddKasbonPegawai, {}) }) }), _jsx(Route, { path: "/history-absen/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(HistoryAbsenPegawaiPage, {}) }) }), _jsx(Route, { path: "/history-lembur/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(HistoryLemburPegawai, {}) }) }), _jsx(Route, { path: "/history-dinas/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(HistoryDinasPegawai, {}) }) }), _jsx(Route, { path: "/pegawai/rapat/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(RapatPegawaiDetail, {}) }) }), _jsx(Route, { path: "/inventory-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(InventoryPegawai, {}) }) }), _jsx(Route, { path: "/add-inventory-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(AddInventoryPegawai, {}) }) }), _jsx(Route, { path: "/other", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(AllMenuPegawai, {}) }) }), _jsx(Route, { path: "/edit-kasbon-pegawai/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(EditKasbonPegawai, {}) }) }), _jsx(Route, { path: "/cuti-izin", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(CutiPegawai, {}) }) }), _jsx(Route, { path: "/rapat-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(RapatPegawai, {}) }) }), _jsx(Route, { path: "/add-cuti-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(AddCutiPegawai, {}) }) }), _jsx(Route, { path: "/add-dokumen-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(AddDokumenPegawai, {}) }) }), _jsx(Route, { path: "/kunjungan-pegawai", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(KunjunganPegawai, {}) }) }), _jsx(Route, { path: "/edit-cuti-pegawai/:id", element: _jsx(ProtectedRoute, { allowedRoles: ["pegawai"], children: _jsx(EditCutiPegawai, {}) }) }), _jsxs(Route, { element: _jsx(ProtectedRoute, { allowedRoles: ["admin", "superadmin"], children: _jsx(AppLayout, {}) }), children: [_jsx(Route, { path: "/dashboard", element: _jsx(Home, {}) }), _jsx(Route, { path: "/profile", element: _jsx(ProfilePage, {}) }), _jsx(Route, { path: "/calendar", element: _jsx(Calendar, {}) }), _jsx(Route, { path: "/blank", element: _jsx(Blank, {}) }), _jsx(Route, { path: "/form-elements", element: _jsx(FormElements, {}) }), _jsx(Route, { path: "/basic-tables", element: _jsx(BasicTables, {}) }), _jsx(Route, { path: "/alerts", element: _jsx(Alerts, {}) }), _jsx(Route, { path: "/avatars", element: _jsx(Avatars, {}) }), _jsx(Route, { path: "/badge", element: _jsx(Badges, {}) }), _jsx(Route, { path: "/buttons", element: _jsx(Buttons, {}) }), _jsx(Route, { path: "/images", element: _jsx(Images, {}) }), _jsx(Route, { path: "/videos", element: _jsx(Videos, {}) }), _jsx(Route, { path: "/line-chart", element: _jsx(LineChart, {}) }), _jsx(Route, { path: "/bar-chart", element: _jsx(BarChart, {}) }), _jsx(Route, { path: "/company", element: _jsx(Company, {}) }), _jsx(Route, { path: "/add-company", element: _jsx(AddCompany, {}) }), _jsx(Route, { path: "/pegawai", element: _jsx(Pegawai, {}) }), _jsx(Route, { path: "/shift-request-approval", element: _jsx(ShiftRequestApproval, {}) }), _jsx(Route, { path: "/add-pegawai", element: _jsx(AddPegawai, {}) }), _jsx(Route, { path: "/edit-pegawai/:id", element: _jsx(EditPegawai, {}) }), _jsx(Route, { path: "/edit-company/:id", element: _jsx(EditCompany, {}) }), _jsx(Route, { path: "/role", element: _jsx(Role, {}) }), _jsx(Route, { path: "/edit-role/:id", element: _jsx(EditRole, {}) }), _jsx(Route, { path: "/add-role", element: _jsx(AddRole, {}) }), _jsx(Route, { path: "/kontrak", element: _jsx(Kontrak, {}) }), _jsx(Route, { path: "/add-kontrak", element: _jsx(AddKontrak, {}) }), _jsx(Route, { path: "/edit-kontrak/:id", element: _jsx(EditKontrak, {}) }), _jsx(Route, { path: "/pegawai-keluar", element: _jsx(PegawaiKeluar, {}) }), _jsx(Route, { path: "/add-pegawai-keluar", element: _jsx(AddPegawaiKeluar, {}) }), _jsx(Route, { path: "/divisi", element: _jsx(DivisiPage, {}) }), _jsx(Route, { path: "/add-divisi", element: _jsx(AddDivisi, {}) }), _jsx(Route, { path: "/edit-divisi/:id", element: _jsx(EditDivisi, {}) }), _jsx(Route, { path: "/shift", element: _jsx(Shift, {}) }), _jsx(Route, { path: "/rekap-data", element: _jsx(RekapData, {}) }), _jsx(Route, { path: "/add-shift", element: _jsx(AddShift, {}) }), _jsx(Route, { path: "/edit-shift/:id", element: _jsx(EditShift, {}) }), _jsx(Route, { path: "/lokasi", element: _jsx(LokasiPage, {}) }), _jsx(Route, { path: "/add-lokasi", element: _jsx(AddLokasi, {}) }), _jsx(Route, { path: "/edit-lokasi/:id", element: _jsx(EditLokasi, {}) }), _jsx(Route, { path: "/cuti", element: _jsx(CutiPage, {}) }), _jsx(Route, { path: "/add-cuti", element: _jsx(AddCuti, {}) }), _jsx(Route, { path: "/penugasan", element: _jsx(Penugasan, {}) }), _jsx(Route, { path: "/add-penugasan", element: _jsx(AddPenugasan, {}) }), _jsx(Route, { path: "/edit-penugasan/:id", element: _jsx(EditPenugasan, {}) }), _jsx(Route, { path: "/rapat", element: _jsx(Rapat, {}) }), _jsx(Route, { path: "/add-rapat", element: _jsx(AddRapat, {}) }), _jsx(Route, { path: "/edit-rapat/:id", element: _jsx(EditRapat, {}) }), _jsx(Route, { path: "/jenis-kinerja", element: _jsx(JenisKinerja, {}) }), _jsx(Route, { path: "/add-jenis-kinerja", element: _jsx(AddJenisKinerja, {}) }), _jsx(Route, { path: "/edit-jenis-kinerja/:id", element: _jsx(EditJenisKinerja, {}) }), _jsx(Route, { path: "/inventory", element: _jsx(InventoryPage, {}) }), _jsx(Route, { path: "/add-inventory", element: _jsx(AddInventory, {}) }), _jsx(Route, { path: "/laporan-kinerja", element: _jsx(LaporanKinerja, {}) }), _jsx(Route, { path: "/edit-inventory/:id", element: _jsx(EditInventory, {}) }), _jsx(Route, { path: "/kinerja-pegawai", element: _jsx(KinerjaPegawaiPage, {}) }), _jsx(Route, { path: "/laporan-kerja", element: _jsx(LaporanKerjaPage, {}) }), _jsx(Route, { path: "/dokumen-pegawai", element: _jsx(Dokumen, {}) }), _jsx(Route, { path: "/add-dokumen-pegawai", element: _jsx(AddDokumen, {}) }), _jsx(Route, { path: "/edit-dokumen-pegawai/:id", element: _jsx(EditDokumen, {}) }), _jsx(Route, { path: "/data-absen", element: _jsx(DataAbsen, {}) }), _jsx(Route, { path: "/edit-absen/:id", element: _jsx(EditAbsen, {}) }), _jsx(Route, { path: "/kasbon", element: _jsx(Kasbon, {}) }), _jsx(Route, { path: "/add-kasbon", element: _jsx(AddKasbon, {}) }), _jsx(Route, { path: "/edit-kasbon/:id", element: _jsx(EditKasbon, {}) }), _jsx(Route, { path: "/data-dinas-luar", element: _jsx(DataDinasLuar, {}) }), _jsx(Route, { path: "/kategori-reimbursement", element: _jsx(KategoriReimbursement, {}) }), _jsx(Route, { path: "/add-kategori-reimbursement", element: _jsx(AddKategoriReimbursement, {}) }), _jsx(Route, { path: "/edit-kategori-reimbursement/:id", element: _jsx(EditKategoriReimbursement, {}) }), _jsx(Route, { path: "/berita", element: _jsx(BeritaPage, {}) }), _jsx(Route, { path: "/add-berita", element: _jsx(AddBerita, {}) }), _jsx(Route, { path: "/edit-berita/:id", element: _jsx(EditBerita, {}) }), _jsx(Route, { path: "/reimbursement", element: _jsx(Reimbursements, {}) }), _jsx(Route, { path: "/add-reimbursement", element: _jsx(AddReimbursement, {}) }), _jsx(Route, { path: "/input-shift/:id", element: _jsx(AddShiftMapping, {}) }), _jsx(Route, { path: "/input-dinas-luar/:id", element: _jsx(AddDinasLuarMapping, {}) }), _jsx(Route, { path: "/lembur", element: _jsx(LemburPegawaiPage, {}) }), _jsx(Route, { path: "/kunjungan", element: _jsx(KunjunganPage, {}) }), _jsx(Route, { path: "/add-kunjungan", element: _jsx(AddKunjungan, {}) }), _jsx(Route, { path: "/kunjungan/:id/visit-out", element: _jsx(VisitOutKunjungan, {}) }), _jsx(Route, { path: "/payroll", element: _jsx(Payroll, {}) }), _jsx(Route, { path: "/payroll/edit/:payrollId", element: _jsx(EditPayrollPegawai, {}) }), _jsx(Route, { path: "/kontrak-kerja/:pegawaiId", element: _jsx(KontrakPegawai, {}) }), _jsx(Route, { path: "/notifications", element: _jsx(Notification, {}) }), _jsx(Route, { path: "/face-recognition/:id", element: _jsx(FaceRecognition, {}) }), _jsx(Route, { path: "/hitung-gaji/:pegawaiId", element: _jsx(HitungGajiPegawai, {}) }), _jsx(Route, { path: "/data-lembur", element: _jsx(DataLembur, {}) }), _jsx(Route, { path: "/pegawai/dashboard", element: _jsx(PegawaiShiftPage, {}) }), _jsx(Route, { path: "/dinas-luar", element: _jsx(DinasLuarPegawaiPage, {}) }), _jsx(Route, { path: "/shift-mapping/pegawai/:id", element: _jsx(JadwalShiftPegawai, {}) }), _jsx(Route, { path: "/face-recognition", element: _jsx(FaceEnroll, {}) }), _jsx(Route, { path: "/contoh", element: _jsx(PegawaiForm, {}) })] }), _jsx(Route, { path: "*", element: _jsx(NotFound, {}) })] })] }));
}
